import { Concept, ReinforcementUnit, StudySession, Question, Note, LearnerProgress, Topic } from '@/types/study';

export const mockTopics: Topic[] = [
  {
    id: 't1',
    name: 'Biology 101',
    description: 'Introduction to biological concepts and life processes',
    color: 'hsl(var(--stable))',
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
  {
    id: 't2',
    name: 'Genetics & Evolution',
    description: 'DNA, heredity, and evolutionary principles',
    color: 'hsl(var(--accent))',
    createdAt: new Date(Date.now() - 86400000 * 20),
  },
];

export const mockConcepts: Concept[] = [
  {
    id: 'c1',
    name: 'Photosynthesis',
    description: 'The process by which plants convert light energy into chemical energy',
    topicId: 't1',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c2',
    name: 'Cellular Respiration',
    description: 'The process by which cells break down glucose to produce ATP',
    topicId: 't1',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c3',
    name: 'DNA Replication',
    description: 'The biological process of producing two identical DNA molecules',
    topicId: 't2',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c4',
    name: 'Mitosis',
    description: 'Cell division resulting in two identical daughter cells',
    topicId: 't2',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c5',
    name: 'Natural Selection',
    description: 'The differential survival and reproduction of individuals',
    topicId: null, // Uncategorized
    parentId: null,
    reinforcementUnits: [],
  },
];

export const mockRUs: ReinforcementUnit[] = [
  {
    id: 'ru1',
    conceptId: 'c1',
    claim: 'Chlorophyll absorbs light primarily in the blue and red wavelengths',
    context: 'Chapter 8: Photosynthesis',
    state: 'stable',
    stabilityScore: 0.92,
    reinforcementCount: 8,
    lastReinforced: new Date(Date.now() - 86400000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 14),
    dependencies: [],
  },
  {
    id: 'ru2',
    conceptId: 'c1',
    claim: 'The Calvin Cycle occurs in the stroma of chloroplasts',
    context: 'Chapter 8: Photosynthesis',
    state: 'stabilizing',
    stabilityScore: 0.65,
    reinforcementCount: 4,
    lastReinforced: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000 * 7),
    dependencies: ['ru1'],
  },
  {
    id: 'ru3',
    conceptId: 'c2',
    claim: 'Glycolysis produces 2 ATP and 2 NADH per glucose molecule',
    context: 'Chapter 9: Cellular Respiration',
    state: 'unstable',
    stabilityScore: 0.35,
    reinforcementCount: 2,
    lastReinforced: new Date(Date.now() - 86400000 * 3),
    createdAt: new Date(Date.now() - 86400000 * 5),
    dependencies: [],
  },
  {
    id: 'ru4',
    conceptId: 'c3',
    claim: 'DNA polymerase synthesizes new DNA in the 5\' to 3\' direction',
    context: 'Chapter 16: DNA Replication',
    state: 'introduced',
    stabilityScore: 0.1,
    reinforcementCount: 0,
    lastReinforced: null,
    createdAt: new Date(),
    dependencies: [],
  },
  {
    id: 'ru5',
    conceptId: 'c4',
    claim: 'Prophase is characterized by chromatin condensation into chromosomes',
    context: 'Chapter 12: The Cell Cycle',
    state: 'reinforced',
    stabilityScore: 0.5,
    reinforcementCount: 3,
    lastReinforced: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000 * 4),
    dependencies: ['ru4'],
  },
  {
    id: 'ru6',
    conceptId: 'c5',
    claim: 'Fitness in evolutionary terms refers to reproductive success, not physical strength',
    context: 'Chapter 22: Evolution',
    state: 'stable',
    stabilityScore: 0.88,
    reinforcementCount: 6,
    lastReinforced: new Date(Date.now() - 86400000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 21),
    dependencies: [],
  },
];

export const mockSessions: StudySession[] = [
  {
    id: 's1',
    title: 'Photosynthesis Deep Dive',
    type: 'reading',
    conceptIds: ['c1'],
    progress: 100,
    startedAt: new Date(Date.now() - 86400000 * 3),
    completedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: 's2',
    title: 'Cell Biology Quiz',
    type: 'quiz',
    conceptIds: ['c2', 'c4'],
    progress: 75,
    startedAt: new Date(Date.now() - 86400000),
    completedAt: null,
  },
  {
    id: 's3',
    title: 'DNA Replication Video',
    type: 'video',
    conceptIds: ['c3'],
    progress: 30,
    startedAt: new Date(),
    completedAt: null,
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    ruId: 'ru3',
    type: 'recall',
    prompt: 'How many ATP molecules are produced during glycolysis from one glucose molecule?',
    options: ['1 ATP', '2 ATP', '4 ATP', '36 ATP'],
    correctAnswer: '2 ATP',
    explanation: 'Glycolysis produces a net gain of 2 ATP molecules per glucose. While 4 ATP are produced, 2 are consumed in the investment phase.',
  },
  {
    id: 'q2',
    ruId: 'ru2',
    type: 'application',
    prompt: 'If a plant cell\'s stroma was damaged, which part of photosynthesis would be most affected?',
    options: ['Light reactions', 'Calvin Cycle', 'Water splitting', 'Electron transport'],
    correctAnswer: 'Calvin Cycle',
    explanation: 'The Calvin Cycle occurs in the stroma, so damage to this region would directly affect carbon fixation.',
  },
  {
    id: 'q3',
    ruId: 'ru5',
    type: 'disambiguation',
    prompt: 'What distinguishes prophase from other phases of mitosis?',
    options: [
      'Chromosomes align at the cell equator',
      'Chromatin condenses into visible chromosomes',
      'Sister chromatids separate',
      'Nuclear envelope reforms',
    ],
    correctAnswer: 'Chromatin condenses into visible chromosomes',
    explanation: 'Prophase is specifically characterized by chromatin condensation. Metaphase involves alignment, anaphase involves separation, and telophase involves nuclear envelope reformation.',
  },
];

export const mockNotes: Note[] = [
  {
    id: 'n1',
    content: 'The light-independent reactions were formerly called "dark reactions" but this is misleading - they don\'t require darkness.',
    conceptId: 'c1',
    ruId: 'ru2',
    isAIGenerated: true,
    createdAt: new Date(Date.now() - 86400000 * 2),
    anchorPosition: 120,
  },
  {
    id: 'n2',
    content: 'Remember: glycolysis = glucose splitting. The prefix "glyco" means sugar and "lysis" means splitting.',
    conceptId: 'c2',
    ruId: 'ru3',
    isAIGenerated: false,
    createdAt: new Date(Date.now() - 86400000),
  },
];

export const mockProgress: LearnerProgress = {
  totalConcepts: 5,
  stableConcepts: 2,
  needsReinforcement: 2,
  recentSessions: 3,
  streakDays: 7,
  totalStudyTime: 245,
};
