import { Concept, ReinforcementUnit, StudySession, Question, Note, LearnerProgress, Topic, Resource } from '@/types/study';

export const mockTopics: Topic[] = [
  {
    id: 't1',
    name: 'Biology 101',
    description: 'Introduction to biological concepts and life processes',
    color: 'hsl(var(--stable))',
    createdAt: new Date(Date.now() - 86400000 * 30),
  },
  {
    id: 't2',
    name: 'Genetics & Evolution',
    description: 'DNA, heredity, and evolutionary principles',
    color: 'hsl(var(--accent))',
    createdAt: new Date(Date.now() - 86400000 * 20),
  },
];

export const mockConcepts: Concept[] = [
  {
    id: 'c1',
    name: 'Photosynthesis',
    description: 'The process by which plants convert light energy into chemical energy',
    topicId: 't1',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c2',
    name: 'Cellular Respiration',
    description: 'The process by which cells break down glucose to produce ATP',
    topicId: 't1',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c3',
    name: 'DNA Replication',
    description: 'The biological process of producing two identical DNA molecules',
    topicId: 't2',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c4',
    name: 'Mitosis',
    description: 'Cell division resulting in two identical daughter cells',
    topicId: 't2',
    parentId: null,
    reinforcementUnits: [],
  },
  {
    id: 'c5',
    name: 'Natural Selection',
    description: 'The differential survival and reproduction of individuals',
    topicId: null, // Uncategorized
    parentId: null,
    reinforcementUnits: [],
  },
];

export const mockRUs: ReinforcementUnit[] = [
  {
    id: 'ru1',
    conceptId: 'c1',
    claim: 'Chlorophyll absorbs light primarily in the blue and red wavelengths',
    context: 'Chapter 8: Photosynthesis',
    state: 'stable',
    stabilityScore: 0.92,
    reinforcementCount: 8,
    lastReinforced: new Date(Date.now() - 86400000 * 2),
    createdAt: new Date(Date.now() - 86400000 * 14),
    dependencies: [],
  },
  {
    id: 'ru2',
    conceptId: 'c1',
    claim: 'The Calvin Cycle occurs in the stroma of chloroplasts',
    context: 'Chapter 8: Photosynthesis',
    state: 'stabilizing',
    stabilityScore: 0.65,
    reinforcementCount: 4,
    lastReinforced: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000 * 7),
    dependencies: ['ru1'],
  },
  {
    id: 'ru3',
    conceptId: 'c2',
    claim: 'Glycolysis produces 2 ATP and 2 NADH per glucose molecule',
    context: 'Chapter 9: Cellular Respiration',
    state: 'unstable',
    stabilityScore: 0.35,
    reinforcementCount: 2,
    lastReinforced: new Date(Date.now() - 86400000 * 3),
    createdAt: new Date(Date.now() - 86400000 * 5),
    dependencies: [],
  },
  {
    id: 'ru4',
    conceptId: 'c3',
    claim: 'DNA polymerase synthesizes new DNA in the 5\' to 3\' direction',
    context: 'Chapter 16: DNA Replication',
    state: 'introduced',
    stabilityScore: 0.1,
    reinforcementCount: 0,
    lastReinforced: null,
    createdAt: new Date(),
    dependencies: [],
  },
  {
    id: 'ru5',
    conceptId: 'c4',
    claim: 'Prophase is characterized by chromatin condensation into chromosomes',
    context: 'Chapter 12: The Cell Cycle',
    state: 'reinforced',
    stabilityScore: 0.5,
    reinforcementCount: 3,
    lastReinforced: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000 * 4),
    dependencies: ['ru4'],
  },
  {
    id: 'ru6',
    conceptId: 'c5',
    claim: 'Fitness in evolutionary terms refers to reproductive success, not physical strength',
    context: 'Chapter 22: Evolution',
    state: 'stable',
    stabilityScore: 0.88,
    reinforcementCount: 6,
    lastReinforced: new Date(Date.now() - 86400000 * 5),
    createdAt: new Date(Date.now() - 86400000 * 21),
    dependencies: [],
  },
];

export const mockResources: Resource[] = [
  {
    id: 'r1',
    title: 'Chapter 8: Photosynthesis (Campbell Biology)',
    type: 'textbook',
    topicId: 't1',
    conceptIds: ['c1'],
    addedAt: new Date(Date.now() - 86400000 * 14),
  },
  {
    id: 'r2',
    title: 'Cellular Respiration Lecture',
    type: 'video',
    url: 'https://youtube.com/watch?v=example1',
    topicId: 't1',
    conceptIds: ['c2'],
    addedAt: new Date(Date.now() - 86400000 * 10),
  },
  {
    id: 'r3',
    title: 'MIT OCW: ATP Synthesis',
    type: 'lecture',
    url: 'https://ocw.mit.edu/example',
    topicId: 't1',
    conceptIds: ['c1', 'c2'],
    addedAt: new Date(Date.now() - 86400000 * 7),
  },
  {
    id: 'r4',
    title: 'DNA Replication Animation',
    type: 'video',
    url: 'https://youtube.com/watch?v=example2',
    topicId: 't2',
    conceptIds: ['c3'],
    addedAt: new Date(Date.now() - 86400000 * 5),
  },
  {
    id: 'r5',
    title: 'Cell Cycle PDF Notes',
    type: 'pdf',
    topicId: 't2',
    conceptIds: ['c4'],
    addedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: 'r6',
    title: 'Evolution & Natural Selection Article',
    type: 'article',
    url: 'https://nature.com/example',
    topicId: 't2',
    conceptIds: ['c5'],
    addedAt: new Date(Date.now() - 86400000 * 2),
  },
];

export const mockSessions: StudySession[] = [
  {
    id: 's1',
    title: 'Photosynthesis Deep Dive',
    type: 'reading',
    conceptIds: ['c1'],
    progress: 100,
    startedAt: new Date(Date.now() - 86400000 * 3),
    completedAt: new Date(Date.now() - 86400000 * 3),
  },
  {
    id: 's2',
    title: 'Cell Biology Quiz',
    type: 'quiz',
    conceptIds: ['c2', 'c4'],
    progress: 75,
    startedAt: new Date(Date.now() - 86400000),
    completedAt: null,
  },
  {
    id: 's3',
    title: 'DNA Replication Video',
    type: 'video',
    conceptIds: ['c3'],
    progress: 30,
    startedAt: new Date(),
    completedAt: null,
  },
];

export const mockQuestions: Question[] = [
  // Photosynthesis (c1) - ru1 questions
  {
    id: 'q1',
    ruId: 'ru1',
    type: 'recall',
    prompt: 'Which wavelengths of light does chlorophyll absorb most effectively?',
    options: ['Green and yellow', 'Blue and red', 'Orange and purple', 'All wavelengths equally'],
    correctAnswer: 'Blue and red',
    explanation: 'Chlorophyll absorbs light primarily in the blue (430-450nm) and red (640-680nm) wavelengths, reflecting green light which is why plants appear green.',
  },
  {
    id: 'q2',
    ruId: 'ru1',
    type: 'application',
    prompt: 'Why do plants appear green to our eyes?',
    options: [
      'They absorb green light',
      'They reflect green light',
      'They emit green light',
      'Chlorophyll is transparent to all colors',
    ],
    correctAnswer: 'They reflect green light',
    explanation: 'Since chlorophyll absorbs blue and red wavelengths, it reflects green light back to our eyes, making plants appear green.',
  },
  {
    id: 'q3',
    ruId: 'ru1',
    type: 'disambiguation',
    prompt: 'What is the primary role of chlorophyll in photosynthesis?',
    options: [
      'To store glucose',
      'To capture light energy',
      'To transport water',
      'To produce carbon dioxide',
    ],
    correctAnswer: 'To capture light energy',
    explanation: 'Chlorophyll is a pigment that captures light energy and converts it to chemical energy during the light reactions of photosynthesis.',
  },
  // Photosynthesis (c1) - ru2 questions
  {
    id: 'q4',
    ruId: 'ru2',
    type: 'recall',
    prompt: 'Where does the Calvin Cycle take place within the chloroplast?',
    options: ['Thylakoid membrane', 'Stroma', 'Outer membrane', 'Intermembrane space'],
    correctAnswer: 'Stroma',
    explanation: 'The Calvin Cycle (light-independent reactions) occurs in the stroma, the fluid-filled space surrounding the thylakoids.',
  },
  {
    id: 'q5',
    ruId: 'ru2',
    type: 'application',
    prompt: 'If a plant cell\'s stroma was damaged, which part of photosynthesis would be most affected?',
    options: ['Light reactions', 'Calvin Cycle', 'Water splitting', 'Electron transport'],
    correctAnswer: 'Calvin Cycle',
    explanation: 'The Calvin Cycle occurs in the stroma, so damage to this region would directly affect carbon fixation.',
  },
  {
    id: 'q6',
    ruId: 'ru2',
    type: 'recall',
    prompt: 'What is another name for the Calvin Cycle?',
    options: ['Light reactions', 'Light-independent reactions', 'Krebs cycle', 'Glycolysis'],
    correctAnswer: 'Light-independent reactions',
    explanation: 'The Calvin Cycle is also called the light-independent reactions because it does not directly require light, though it depends on products from the light reactions.',
  },
  // Cellular Respiration (c2) - ru3 questions
  {
    id: 'q7',
    ruId: 'ru3',
    type: 'recall',
    prompt: 'How many ATP molecules are produced during glycolysis from one glucose molecule?',
    options: ['1 ATP', '2 ATP', '4 ATP', '36 ATP'],
    correctAnswer: '2 ATP',
    explanation: 'Glycolysis produces a net gain of 2 ATP molecules per glucose. While 4 ATP are produced, 2 are consumed in the investment phase.',
  },
  {
    id: 'q8',
    ruId: 'ru3',
    type: 'recall',
    prompt: 'Where does glycolysis occur in the cell?',
    options: ['Mitochondria', 'Cytoplasm', 'Nucleus', 'Endoplasmic reticulum'],
    correctAnswer: 'Cytoplasm',
    explanation: 'Glycolysis occurs in the cytoplasm of the cell and does not require oxygen or any organelles.',
  },
  {
    id: 'q9',
    ruId: 'ru3',
    type: 'application',
    prompt: 'Why is glycolysis considered an anaerobic process?',
    options: [
      'It produces oxygen',
      'It requires oxygen',
      'It does not require oxygen',
      'It only occurs in anaerobic organisms',
    ],
    correctAnswer: 'It does not require oxygen',
    explanation: 'Glycolysis can occur with or without oxygen present, making it an anaerobic process that all cells can perform.',
  },
  // DNA Replication (c3) - ru4 questions
  {
    id: 'q10',
    ruId: 'ru4',
    type: 'recall',
    prompt: 'In which direction does DNA polymerase synthesize new DNA?',
    options: ['3\' to 5\'', '5\' to 3\'', 'Both directions', 'Random direction'],
    correctAnswer: '5\' to 3\'',
    explanation: 'DNA polymerase can only add nucleotides to the 3\' end of a growing strand, so synthesis always proceeds in the 5\' to 3\' direction.',
  },
  {
    id: 'q11',
    ruId: 'ru4',
    type: 'application',
    prompt: 'Why is there a leading strand and a lagging strand during DNA replication?',
    options: [
      'Different polymerases work on each strand',
      'DNA polymerase can only synthesize 5\' to 3\'',
      'One strand replicates faster',
      'The strands have different bases',
    ],
    correctAnswer: 'DNA polymerase can only synthesize 5\' to 3\'',
    explanation: 'Since DNA strands are antiparallel and polymerase only works 5\' to 3\', one strand (lagging) must be synthesized in fragments.',
  },
  {
    id: 'q12',
    ruId: 'ru4',
    type: 'disambiguation',
    prompt: 'What are Okazaki fragments?',
    options: [
      'Pieces of the leading strand',
      'Short segments of the lagging strand',
      'Damaged DNA sequences',
      'RNA primers',
    ],
    correctAnswer: 'Short segments of the lagging strand',
    explanation: 'Okazaki fragments are short, newly synthesized DNA segments on the lagging strand, later joined by DNA ligase.',
  },
  // Mitosis (c4) - ru5 questions
  {
    id: 'q13',
    ruId: 'ru5',
    type: 'recall',
    prompt: 'What happens during prophase of mitosis?',
    options: [
      'Chromosomes align at the cell equator',
      'Chromatin condenses into visible chromosomes',
      'Sister chromatids separate',
      'Nuclear envelope reforms',
    ],
    correctAnswer: 'Chromatin condenses into visible chromosomes',
    explanation: 'Prophase is specifically characterized by chromatin condensation. Metaphase involves alignment, anaphase involves separation, and telophase involves nuclear envelope reformation.',
  },
  {
    id: 'q14',
    ruId: 'ru5',
    type: 'recall',
    prompt: 'What structure begins to form during prophase to help separate chromosomes?',
    options: ['Cell plate', 'Spindle fibers', 'Nuclear envelope', 'Centrioles'],
    correctAnswer: 'Spindle fibers',
    explanation: 'During prophase, spindle fibers begin forming from the centrosomes, which will later attach to chromosomes and pull them apart.',
  },
  {
    id: 'q15',
    ruId: 'ru5',
    type: 'application',
    prompt: 'If a drug prevented chromatin condensation, which phase of mitosis would be blocked?',
    options: ['Metaphase', 'Anaphase', 'Prophase', 'Telophase'],
    correctAnswer: 'Prophase',
    explanation: 'Chromatin condensation is a defining event of prophase, so blocking it would prevent the cell from progressing past this phase.',
  },
  // Natural Selection (c5) - ru6 questions
  {
    id: 'q16',
    ruId: 'ru6',
    type: 'recall',
    prompt: 'In evolutionary terms, what does "fitness" refer to?',
    options: [
      'Physical strength',
      'Reproductive success',
      'Speed and agility',
      'Ability to survive predators',
    ],
    correctAnswer: 'Reproductive success',
    explanation: 'Evolutionary fitness refers to an organism\'s ability to survive and reproduce, passing genes to the next generation.',
  },
  {
    id: 'q17',
    ruId: 'ru6',
    type: 'disambiguation',
    prompt: 'Why might a physically weaker organism have higher evolutionary fitness?',
    options: [
      'It cannot happen',
      'Physical strength determines fitness',
      'Fitness is about reproductive success, not strength',
      'Weaker organisms live longer',
    ],
    correctAnswer: 'Fitness is about reproductive success, not strength',
    explanation: 'An organism that reproduces more successfully has higher fitness, regardless of physical attributes like strength.',
  },
  {
    id: 'q18',
    ruId: 'ru6',
    type: 'application',
    prompt: 'A bird species with larger beaks survives a drought better because they can crack harder seeds. This is an example of:',
    options: ['Genetic drift', 'Natural selection', 'Mutation', 'Gene flow'],
    correctAnswer: 'Natural selection',
    explanation: 'This is natural selection in action - individuals with traits better suited to the environment (larger beaks) survive and reproduce more.',
  },
];

export const mockNotes: Note[] = [
  {
    id: 'n1',
    content: 'The light-independent reactions were formerly called "dark reactions" but this is misleading - they don\'t require darkness.',
    conceptId: 'c1',
    ruId: 'ru2',
    isAIGenerated: true,
    createdAt: new Date(Date.now() - 86400000 * 2),
    anchorPosition: 120,
  },
  {
    id: 'n2',
    content: 'Remember: glycolysis = glucose splitting. The prefix "glyco" means sugar and "lysis" means splitting.',
    conceptId: 'c2',
    ruId: 'ru3',
    isAIGenerated: false,
    createdAt: new Date(Date.now() - 86400000),
  },
];

export const mockProgress: LearnerProgress = {
  totalConcepts: 5,
  stableConcepts: 2,
  needsReinforcement: 2,
  recentSessions: 3,
  streakDays: 7,
  totalStudyTime: 245,
};
